#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr 21 20:01:08 2019

@author: tc
"""

ipdb> print(ccxt.binance.has)

{'cancelAllOrders': False, 'cancelOrder': True, 'cancelOrders': False, 'CORS': False, 'createDepositAddress': False, 'createLimitOrder': True, 'createMarketOrder': True, 'createOrder': True, 'deposit': False, 'editOrder': 'emulated', 'fetchBalance': True, 'fetchClosedOrders': True, 'fetchCurrencies': False, 'fetchDepositAddress': True, 'fetchDeposits': True, 'fetchFundingFees': True, 'fetchL2OrderBook': True, 'fetchLedger': False, 'fetchMarkets': True, 'fetchMyTrades': True, 'fetchOHLCV': True, 'fetchOpenOrders': True, 'fetchOrder': True, 'fetchOrderBook': True, 'fetchOrderBooks': False, 'fetchOrders': True, 'fetchTicker': True, 'fetchTickers': True, 'fetchTrades': True, 'fetchTradingFee': False, 'fetchTradingFees': False, 'fetchFundingFee': False, 'fetchTradingLimits': False, 'fetchTransactions': False, 'fetchWithdrawals': True, 'privateAPI': True, 'publicAPI': True, 'withdraw': True, 'fetchBidsAsks': True}

ipdb> print(self.xch.fetchOpenOrders('TUSD/USDT'))

[{'info':
    {'symbol': 'TUSDUSDT', 'orderId': 16506859, 'clientOrderId': 'web_0686efc46fc8443b92e6745c9a8e88bb', 'price': '0.99210000', 'origQty': '8056.42000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'NEW', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'BUY', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1555880591991, 'updateTime': 1555880591991, 'isWorking': True},
    'id': '16506859',
    'timestamp': 1555880591991,
    'datetime': '2019-04-21T21:03:11.991Z',
    'lastTradeTimestamp': None,
    'symbol': 'TUSD/USDT',
    'type': 'limit',
    'side': 'buy',
    'price': 0.9921,
    'amount': 8056.42,
    'cost': 0.0,
    'average': None,
    'filled': 0.0,
    'remaining': 8056.42,
    'status': 'open',
    'fee': None,
    'trades': None},

    {'info': {'symbol': 'TUSDUSDT', 'orderId': 16506940, 'clientOrderId': 'web_66bcac26fff5491a88e89a28125655af', 'price': '0.99230000', 'origQty': '7999.00000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'NEW', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'BUY', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1555880650047, 'updateTime': 1555880650047, 'isWorking': True}, 'id': '16506940', 'timestamp': 1555880650047, 'datetime': '2019-04-21T21:04:10.047Z', 'lastTradeTimestamp': None, 'symbol': 'TUSD/USDT', 'type': 'limit', 'side': 'buy', 'price': 0.9923, 'amount': 7999.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 7999.0, 'status': 'open', 'fee': None, 'trades': None},

{'info': {'symbol': 'TUSDUSDT', 'orderId': 16506974, 'clientOrderId': 'web_0435a347288a409486ff9c94f6924ada', 'price': '0.99250000', 'origQty': '15154.58000000', 'executedQty': '118.00000000', 'cummulativeQuoteQty': '117.11500000', 'status': 'PARTIALLY_FILLED', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'BUY', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1555880675859, 'updateTime': 1555882053153, 'isWorking': True},
 'id': '16506974',
 'timestamp': 1555880675859,
 'datetime': '2019-04-21T21:04:35.859Z',
 'lastTradeTimestamp': None,
 'symbol': 'TUSD/USDT',
 'type': 'limit',
 'side': 'buy',
 'price': 0.9925,
 'amount': 15154.58,
 'cost': 117.115,
 'average': 0.9924999999999999,
 'filled': 118.0,
 'remaining': 15036.58,
 'status': 'open',
 'fee': None,
 'trades': None}]



ipdb> print(self.xch.fetch_my_trades('TUSD/USDT'))

[{'info':
    {'symbol': 'TUSDUSDT', 'id': 3520002, 'orderId': 16506974, 'price': '0.99250000', 'qty': '118.00000000', 'quoteQty': '117.11500000', 'commission': '0.11800000', 'commissionAsset': 'TUSD', 'time': 1555882053153, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True},
    'timestamp': 1555882053153,
    'datetime': '2019-04-21T21:27:33.153Z',
    'symbol': 'TUSD/USDT',
    'id': '3520002',
    'order': '16506974',
    'type': None,
    'takerOrMaker': 'maker',
    'side': 'buy',
    'price': 0.9925,
    'amount': 118.0,
    'cost': 117.11500000000001,
    'fee': {'cost': 0.118, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520072, 'orderId': 16506974, 'price': '0.99250000', 'qty': '1211.38000000', 'quoteQty': '1202.29465000', 'commission': '1.21138000', 'commissionAsset': 'TUSD', 'time': 1555882217815, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882217815, 'datetime': '2019-04-21T21:30:17.815Z', 'symbol': 'TUSD/USDT', 'id': '3520072', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 1211.38, 'cost': 1202.2946500000003, 'fee': {'cost': 1.21138, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520091, 'orderId': 16506974, 'price': '0.99250000', 'qty': '33.47000000', 'quoteQty': '33.21897500', 'commission': '0.03347000', 'commissionAsset': 'TUSD', 'time': 1555882314012, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882314012, 'datetime': '2019-04-21T21:31:54.012Z', 'symbol': 'TUSD/USDT', 'id': '3520091', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 33.47, 'cost': 33.218975, 'fee': {'cost': 0.03347, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520092, 'orderId': 16506974, 'price': '0.99250000', 'qty': '354.49000000', 'quoteQty': '351.83132500', 'commission': '0.35449000', 'commissionAsset': 'TUSD', 'time': 1555882333209, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882333209, 'datetime': '2019-04-21T21:32:13.209Z', 'symbol': 'TUSD/USDT', 'id': '3520092', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 354.49, 'cost': 351.83132500000005, 'fee': {'cost': 0.35449, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520094, 'orderId': 16506974, 'price': '0.99250000', 'qty': '3309.24000000', 'quoteQty': '3284.42070000', 'commission': '3.30924000', 'commissionAsset': 'TUSD', 'time': 1555882369844, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882369844, 'datetime': '2019-04-21T21:32:49.844Z', 'symbol': 'TUSD/USDT', 'id': '3520094', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 3309.24, 'cost': 3284.4207, 'fee': {'cost': 3.30924, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520095, 'orderId': 16506974, 'price': '0.99250000', 'qty': '1210.96000000', 'quoteQty': '1201.87780000', 'commission': '1.21096000', 'commissionAsset': 'TUSD', 'time': 1555882369944, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882369944, 'datetime': '2019-04-21T21:32:49.944Z', 'symbol': 'TUSD/USDT', 'id': '3520095', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 1210.96, 'cost': 1201.8778000000002, 'fee': {'cost': 1.21096, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520097, 'orderId': 16506974, 'price': '0.99250000', 'qty': '689.19000000', 'quoteQty': '684.02107500', 'commission': '0.68919000', 'commissionAsset': 'TUSD', 'time': 1555882382196, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882382196, 'datetime': '2019-04-21T21:33:02.196Z', 'symbol': 'TUSD/USDT', 'id': '3520097', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 689.19, 'cost': 684.0210750000001, 'fee': {'cost': 0.68919, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520098, 'orderId': 16506974, 'price': '0.99250000', 'qty': '676.40000000', 'quoteQty': '671.32700000', 'commission': '0.67640000', 'commissionAsset': 'TUSD', 'time': 1555882382636, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882382636, 'datetime': '2019-04-21T21:33:02.636Z', 'symbol': 'TUSD/USDT', 'id': '3520098', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 676.4, 'cost': 671.327, 'fee': {'cost': 0.6764, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520099, 'orderId': 16506974, 'price': '0.99250000', 'qty': '718.10000000', 'quoteQty': '712.71425000', 'commission': '0.71810000', 'commissionAsset': 'TUSD', 'time': 1555882383166, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882383166, 'datetime': '2019-04-21T21:33:03.166Z', 'symbol': 'TUSD/USDT', 'id': '3520099', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 718.1, 'cost': 712.7142500000001, 'fee': {'cost': 0.7181, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520100, 'orderId': 16506974, 'price': '0.99250000', 'qty': '718.10000000', 'quoteQty': '712.71425000', 'commission': '0.71810000', 'commissionAsset': 'TUSD', 'time': 1555882383611, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882383611, 'datetime': '2019-04-21T21:33:03.611Z', 'symbol': 'TUSD/USDT', 'id': '3520100', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 718.1, 'cost': 712.7142500000001, 'fee': {'cost': 0.7181, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520101, 'orderId': 16506974, 'price': '0.99250000', 'qty': '845.76000000', 'quoteQty': '839.41680000', 'commission': '0.84576000', 'commissionAsset': 'TUSD', 'time': 1555882384152, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882384152, 'datetime': '2019-04-21T21:33:04.152Z', 'symbol': 'TUSD/USDT', 'id': '3520101', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 845.76, 'cost': 839.4168000000001, 'fee': {'cost': 0.84576, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520102, 'orderId': 16506974, 'price': '0.99250000', 'qty': '698.89000000', 'quoteQty': '693.64832500', 'commission': '0.69889000', 'commissionAsset': 'TUSD', 'time': 1555882385165, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882385165, 'datetime': '2019-04-21T21:33:05.165Z', 'symbol': 'TUSD/USDT', 'id': '3520102', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 698.89, 'cost': 693.648325, 'fee': {'cost': 0.69889, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520103, 'orderId': 16506974, 'price': '0.99250000', 'qty': '698.89000000', 'quoteQty': '693.64832500', 'commission': '0.69889000', 'commissionAsset': 'TUSD', 'time': 1555882386697, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882386697, 'datetime': '2019-04-21T21:33:06.697Z', 'symbol': 'TUSD/USDT', 'id': '3520103', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 698.89, 'cost': 693.648325, 'fee': {'cost': 0.69889, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520104, 'orderId': 16506974, 'price': '0.99250000', 'qty': '880.42000000', 'quoteQty': '873.81685000', 'commission': '0.88042000', 'commissionAsset': 'TUSD', 'time': 1555882387642, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882387642, 'datetime': '2019-04-21T21:33:07.642Z', 'symbol': 'TUSD/USDT', 'id': '3520104', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 880.42, 'cost': 873.81685, 'fee': {'cost': 0.88042, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520105, 'orderId': 16506974, 'price': '0.99250000', 'qty': '880.42000000', 'quoteQty': '873.81685000', 'commission': '0.88042000', 'commissionAsset': 'TUSD', 'time': 1555882388242, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882388242, 'datetime': '2019-04-21T21:33:08.242Z', 'symbol': 'TUSD/USDT', 'id': '3520105', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 880.42, 'cost': 873.81685, 'fee': {'cost': 0.88042, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520106, 'orderId': 16506974, 'price': '0.99250000', 'qty': '932.81000000', 'quoteQty': '925.81392500', 'commission': '0.93281000', 'commissionAsset': 'TUSD', 'time': 1555882388904, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882388904, 'datetime': '2019-04-21T21:33:08.904Z', 'symbol': 'TUSD/USDT', 'id': '3520106', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 932.81, 'cost': 925.813925, 'fee': {'cost': 0.93281, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520107, 'orderId': 16506974, 'price': '0.99250000', 'qty': '932.81000000', 'quoteQty': '925.81392500', 'commission': '0.93281000', 'commissionAsset': 'TUSD', 'time': 1555882389225, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882389225, 'datetime': '2019-04-21T21:33:09.225Z', 'symbol': 'TUSD/USDT', 'id': '3520107', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 932.81, 'cost': 925.813925, 'fee': {'cost': 0.93281, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520108, 'orderId': 16506974, 'price': '0.99250000', 'qty': '245.25000000', 'quoteQty': '243.41062500', 'commission': '0.24525000', 'commissionAsset': 'TUSD', 'time': 1555882390009, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882390009, 'datetime': '2019-04-21T21:33:10.009Z', 'symbol': 'TUSD/USDT', 'id': '3520108', 'order': '16506974', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9925, 'amount': 245.25, 'cost': 243.410625, 'fee': {'cost': 0.24525, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520141, 'orderId': 16506940, 'price': '0.99230000', 'qty': '219.58000000', 'quoteQty': '217.88923400', 'commission': '0.21958000', 'commissionAsset': 'TUSD', 'time': 1555882522692, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882522692, 'datetime': '2019-04-21T21:35:22.692Z', 'symbol': 'TUSD/USDT', 'id': '3520141', 'order': '16506940', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9923, 'amount': 219.58, 'cost': 217.88923400000002, 'fee': {'cost': 0.21958, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520142, 'orderId': 16506940, 'price': '0.99230000', 'qty': '1853.81000000', 'quoteQty': '1839.53566300', 'commission': '1.85381000', 'commissionAsset': 'TUSD', 'time': 1555882522694, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882522694, 'datetime': '2019-04-21T21:35:22.694Z', 'symbol': 'TUSD/USDT', 'id': '3520142', 'order': '16506940', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9923, 'amount': 1853.81, 'cost': 1839.5356629999999, 'fee': {'cost': 1.85381, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520143, 'orderId': 16506940, 'price': '0.99230000', 'qty': '99.89000000', 'quoteQty': '99.12084700', 'commission': '0.09989000', 'commissionAsset': 'TUSD', 'time': 1555882522698, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882522698, 'datetime': '2019-04-21T21:35:22.698Z', 'symbol': 'TUSD/USDT', 'id': '3520143', 'order': '16506940', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9923, 'amount': 99.89, 'cost': 99.120847, 'fee': {'cost': 0.09989, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520144, 'orderId': 16506940, 'price': '0.99230000', 'qty': '3631.92000000', 'quoteQty': '3603.95421600', 'commission': '3.63192000', 'commissionAsset': 'TUSD', 'time': 1555882527512, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882527512, 'datetime': '2019-04-21T21:35:27.512Z', 'symbol': 'TUSD/USDT', 'id': '3520144', 'order': '16506940', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9923, 'amount': 3631.92, 'cost': 3603.954216, 'fee': {'cost': 3.63192, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520145, 'orderId': 16506940, 'price': '0.99230000', 'qty': '2193.80000000', 'quoteQty': '2176.90774000', 'commission': '2.19380000', 'commissionAsset': 'TUSD', 'time': 1555882527513, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882527513, 'datetime': '2019-04-21T21:35:27.513Z', 'symbol': 'TUSD/USDT', 'id': '3520145', 'order': '16506940', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9923, 'amount': 2193.8, 'cost': 2176.90774, 'fee': {'cost': 2.1938, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520169, 'orderId': 16506859, 'price': '0.99210000', 'qty': '1924.68000000', 'quoteQty': '1909.47502800', 'commission': '1.92468000', 'commissionAsset': 'TUSD', 'time': 1555882646947, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882646947, 'datetime': '2019-04-21T21:37:26.947Z', 'symbol': 'TUSD/USDT', 'id': '3520169', 'order': '16506859', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9921, 'amount': 1924.68, 'cost': 1909.475028, 'fee': {'cost': 1.92468, 'currency': 'TUSD'}},
{'info': {'symbol': 'TUSDUSDT', 'id': 3520170, 'orderId': 16506859, 'price': '0.99210000', 'qty': '3809.59000000', 'quoteQty': '3779.49423900', 'commission': '3.80959000', 'commissionAsset': 'TUSD', 'time': 1555882657927, 'isBuyer': True, 'isMaker': True, 'isBestMatch': True}, 'timestamp': 1555882657927, 'datetime': '2019-04-21T21:37:37.927Z', 'symbol': 'TUSD/USDT', 'id': '3520170', 'order': '16506859', 'type': None, 'takerOrMaker': 'maker', 'side': 'buy', 'price': 0.9921, 'amount': 3809.59, 'cost': 3779.494239, 'fee': {'cost': 3.80959, 'currency': 'TUSD'}}]



